server:
  port: 9091
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      

user:
  username: "admin"
  password: "admin"
